color: null
description: null
fieldLayouts:
  ed7bf7d6-055c-4d1a-8a54-3c1d8c21cae9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-19T12:48:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8952572a-e79d-48ec-b8c9-3762274fd560 # Enllaç
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df9494a6-2696-4eaa-a9b0-d3d4194f7e76
            userCondition: null
            warning: null
            width: 100
        name: Contenido
        uid: a311436b-d28c-4e50-aa0d-5436c81050d8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-19T12:49:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b0993479-9c99-451f-8b5b-4116eb1cf405 # Capítols del recurs
            handle: capitols
            includeInCards: false
            instructions: null
            label: Capítols
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d623fad-6ef3-4a3b-851e-88080d14e7a4
            userCondition: null
            warning: null
            width: 100
        name: Relacionats
        uid: 73d275d1-9b9c-400b-9000-b2e4bf496d5e
        userCondition: null
handle: entryRecursEnllac
hasTitleField: false
icon: null
name: 'Entry > Recurs > Enllaç'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
