color: null
description: null
fieldLayouts:
  60f2b654-95bd-43b8-858b-72d136d62460:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-19T11:18:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: db9989c1-e77e-4cd2-bad0-4ec1c0b8249c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-19T11:25:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fe2f4045-02f4-41ad-a175-eb69191a1a05 # CapÃ­tols
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 665a62e2-5f08-43b5-b6ea-933e830ec9f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-19T11:25:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d2399b89-87b2-4f3a-9eb7-e311a405ef62 # Persones
            handle: autors
            includeInCards: false
            instructions: null
            label: Autors
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4647f29-dc6d-4979-ad7c-e0a90c6ddb9b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-01-19T12:31:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d06dc03f-d47f-4a54-a0f4-9d994858f3b7 # Recursos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa7dc345-80e6-4e96-bfee-b6d5df995a86
            userCondition: null
            warning: null
            width: 50
        name: Contenido
        uid: abd7dde8-2dc5-4107-96bc-5c08f386c56f
        userCondition: null
handle: entryLlibre
hasTitleField: true
icon: null
name: 'Entry > Llibre'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
