color: null
description: null
fieldLayouts:
  af3ff9ba-71c4-4aea-8330-270050700097:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-20T12:28:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69664e00-8076-4c4d-84b6-47a79c6c4b4b # Text simple
            handle: pretitol
            includeInCards: false
            instructions: null
            label: Pretítol
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 884dbc6c-0e5c-41f1-bd36-af912e2c2f17
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-01-20T12:28:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1baada73-8057-4a1e-b0a6-ef8a7daa44f4 # Text simple multilinea
            handle: titol
            includeInCards: false
            instructions: null
            label: Títol
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4d2e624-f831-457f-9698-e5c6cec53567
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-01-20T12:28:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d779f0dc-9989-4bfc-a650-2dbbaf83669e # Text ric
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 726a9f46-a7e2-4c77-9c64-34a404189833
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-01-20T12:30:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8221ed7c-fede-4b8e-818d-7755b2a2932a # Items
            handle: lectures
            includeInCards: false
            instructions: null
            label: Lectures
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d57c1bc-a0d4-44aa-acc4-ff37633daa62
            userCondition: null
            warning: null
            width: 100
        name: Contenido
        uid: baa8f27b-929e-4183-a4c9-ec7c867d1cd4
        userCondition: null
handle: slicePublicaCohortItinerari
hasTitleField: false
icon: null
name: 'Slice > Pública > Cohort > Itinerari'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
