color: null
description: null
fieldLayouts:
  67b686fc-d4e2-4b2a-912b-b4df99de5fec:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-20T12:24:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69664e00-8076-4c4d-84b6-47a79c6c4b4b # Text simple
            handle: pretitol
            includeInCards: false
            instructions: null
            label: Pretitol
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08d11331-408e-4bd5-8773-a54fc33f375a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-01-20T12:24:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1baada73-8057-4a1e-b0a6-ef8a7daa44f4 # Text simple multilinea
            handle: titol
            includeInCards: false
            instructions: null
            label: Títol
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4111d328-a990-449d-9119-3397ea114935
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-01-20T12:24:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d779f0dc-9989-4bfc-a650-2dbbaf83669e # Text ric
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc3e3efa-fd2b-4bc4-b743-9c7003982aa3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-20T12:25:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 918df2bf-ce9b-4e16-a354-3ce9c4bedb65 # Imatges
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4552254-2a55-4398-b547-50aad8ea5c3c
            userCondition: null
            warning: null
            width: 50
        name: Contenido
        uid: 038f3637-a813-4bff-bd5d-cc1dbecf3e8d
        userCondition: null
handle: slicePublicaCohortHero
hasTitleField: false
icon: null
name: 'Slice > Pública > Cohort > Hero'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
