color: null
description: null
fieldLayouts:
  55cda95f-c941-4ce4-b5e9-e34354560f6f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-20T12:31:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69664e00-8076-4c4d-84b6-47a79c6c4b4b # Text simple
            handle: pretitol
            includeInCards: false
            instructions: null
            label: Pretítol
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5ba488c-8d7a-4056-900c-caea4f75fb16
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-01-20T12:31:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1baada73-8057-4a1e-b0a6-ef8a7daa44f4 # Text simple multilinea
            handle: titol
            includeInCards: false
            instructions: null
            label: Títol
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf7771ca-1e5f-4c89-a902-688431c3fa18
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-01-20T12:31:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8221ed7c-fede-4b8e-818d-7755b2a2932a # Items
            handle: punts
            includeInCards: false
            instructions: null
            label: Punts
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e0213b4-d0fb-47a0-8dce-fc6aad65d773
            userCondition: null
            warning: null
            width: 100
        name: Contenido
        uid: d6fb3aa7-0250-4efd-be1a-194141a15b14
        userCondition: null
handle: slicePublicaCohortInfo
hasTitleField: false
icon: null
name: 'Slice > Pública > Cohort > Info'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
