altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  62e58d3c-1fa8-4d30-9913-87b4bc1bfa49:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-20T12:23:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 28daac3a-677c-42b2-aa56-ec2c51c0ba69
            userCondition: null
            warning: null
            width: 100
        name: Contenido
        uid: e970e612-1f82-4f6a-931a-9c3802ecfd05
        userCondition: null
fs: imatge
handle: imatge
name: Imatge
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
