columnSuffix: null
handle: capitolsDelRecurs
instructions: null
name: 'Capítols del recurs'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  readOnly: ''
  selectionLabel: null
  showCardsInGrid: true
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'section:8576967a-62f7-4292-be16-7feac208effb' # Entry > Capítol
  targetFieldId: d06dc03f-d47f-4a54-a0f4-9d994858f3b7 # Recursos
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: robuust\reverserelations\fields\ReverseEntries
