columnSuffix: null
handle: cohortsFormacio
instructions: null
name: 'Cohorts de la Formació'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  readOnly: ''
  selectionLabel: null
  showCardsInGrid: true
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'section:1dc636cd-f202-42d7-ae97-07c5dc1b248f' # Entry > Cohort
  targetFieldId: ab40316b-e88b-40c8-99d1-15d6c2a8aedc # Formació
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: robuust\reverserelations\fields\ReverseEntries
