columnSuffix: null
handle: enllac
instructions: null
name: Enlla√ß
searchable: false
settings:
  advancedFields:
    - target
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - '1'
            -
              - allowAnchors
              - '1'
            -
              - allowCustomSchemes
              - '1'
      -
        - asset
        -
          __assoc__:
            -
              - allowedKinds
              - '*'
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
  types:
    - entry
    - url
    - asset
    - category
    - email
    - sms
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
