columnSuffix: null
handle: taula
instructions: null
name: Taula
searchable: false
settings:
  addRowLabel: 'Agregar una fila'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - TÃ­tol
            -
              - handle
              - titol
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Text
            -
              - handle
              - text
            -
              - width
              - ''
            -
              - type
              - multiline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: site
type: craft\fields\Table
