dateModified: 1768827673
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Canales
      key: 'heading:dee38328-fdd5-4355-9d58-8675402c21af'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:c6bc2c8d-cdc6-477a-9261-a424e03645a9' # Entry > Llibre
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'section:eb6ec4e7-328d-48ed-902e-9bad2fb003e3' # Entry > Persona
      type: native
    -
      key: 'section:8576967a-62f7-4292-be16-7feac208effb' # Entry > Capítol
      type: native
    -
      key: 'section:5e1d59cf-ace3-4bd7-9802-5ac75f3f0f28' # Entry > Recurs
      type: native
email:
  fromEmail: oriolnoya@gmail.com
  fromName: 'En present'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1baada73-8057-4a1e-b0a6-ef8a7daa44f4: 'Text simple multilinea' # Text simple multilinea
    2c316bdb-68c4-4420-97b1-e85e1c5d681e: 'Entry > Capítol' # Entry > Capítol
    4ced6010-876d-490b-af80-300cb878dcbf: 'Entry > Llibre' # Entry > Llibre
    5e1d59cf-ace3-4bd7-9802-5ac75f3f0f28: 'Entry > Recurs' # Entry > Recurs
    5e4bcb36-5b6e-4752-b39a-9ec111473877: 'Part privada' # Part privada
    6ad2c898-0cf3-4058-aa22-7c1986e5b049: 'Entry > Persona' # Entry > Persona
    7b4f3e82-417a-4f8f-a415-b801acb41d7c: 'Llibres de la persona' # Llibres de la persona
    7e586577-127c-46df-b92d-db3f6f2b3d6f: 'Entry > Recurs > Pregunta' # Entry > Recurs > Pregunta
    033dacc8-df7a-4550-a5fc-ebae2179714e: 'Privada [CA]' # Privada [CA]
    2941c679-5c1e-45e1-b49a-193c180696e4: Simple # Simple
    69664e00-8076-4c4d-84b6-47a79c6c4b4b: 'Text simple' # Text simple
    8576967a-62f7-4292-be16-7feac208effb: 'Entry > Capítol' # Entry > Capítol
    8952572a-e79d-48ec-b8c9-3762274fd560: Enllaç # Enllaç
    39561329-9989-45fe-b242-218cbe6b3e40: 'Part pública' # Part pública
    b0f3ccf5-cdc5-47e5-bb3e-e83014e862a3: 'Entry > Recurs > Resum' # Entry > Recurs > Resum
    b0588da5-48d5-4745-abed-464ae1811973: 'Entry > Recurs > Enllaç' # Entry > Recurs > Enllaç
    b0993479-9c99-451f-8b5b-4116eb1cf405: 'Capítols del recurs' # Capítols del recurs
    c6bc2c8d-cdc6-477a-9261-a424e03645a9: 'Entry > Llibre' # Entry > Llibre
    d06dc03f-d47f-4a54-a0f4-9d994858f3b7: Recursos # Recursos
    d779f0dc-9989-4bfc-a650-2dbbaf83669e: 'Text ric' # Text ric
    d2399b89-87b2-4f3a-9eb7-e311a405ef62: Persones # Persones
    ddca9896-fed1-46a0-9f54-6c6f34565ed3: 'Llibre del capítol' # Llibre del capítol
    eb6ec4e7-328d-48ed-902e-9bad2fb003e3: 'Entry > Persona' # Entry > Persona
    ee778f01-15ae-43a3-b335-e37f288be176: 'Pública [ES]' # Pública [ES]
    f55d6348-8ad5-414d-88c7-a50044a897c1: 'Privada [ES]' # Privada [ES]
    f55331ba-c158-4c5c-8858-e94fe653dbc5: Full # Full
    fe2f4045-02f4-41ad-a175-eb69191a1a05: Capítols # Capítols
    ff486d12-d94d-4a7f-b506-57c5a3c2e2e0: 'Pública [CA]' # Pública [CA]
plugins:
  author-toolbar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  reverserelations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  seomatic:
    edition: standard
    enabled: true
    licenseKey: ITHZDLWPGR4F99FG11MNVC7C
    schemaVersion: 3.0.13
system:
  edition: solo
  live: true
  name: 'En present'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
