dateModified: 1768822122
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Canales
      key: 'heading:dee38328-fdd5-4355-9d58-8675402c21af'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:c6bc2c8d-cdc6-477a-9261-a424e03645a9' # Entry > Llibre
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: 'section:eb6ec4e7-328d-48ed-902e-9bad2fb003e3' # Entry > Persona
      type: native
    -
      key: 'section:8576967a-62f7-4292-be16-7feac208effb' # Entry > Capítol
      type: native
email:
  fromEmail: oriolnoya@gmail.com
  fromName: 'En present'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1baada73-8057-4a1e-b0a6-ef8a7daa44f4: 'Text simple multilinea' # Text simple multilinea
    2c316bdb-68c4-4420-97b1-e85e1c5d681e: 'Entry > Capítol' # Entry > Capítol
    4ced6010-876d-490b-af80-300cb878dcbf: 'Entry > Llibre' # Entry > Llibre
    6ad2c898-0cf3-4058-aa22-7c1986e5b049: 'Entry > Persona' # Entry > Persona
    2941c679-5c1e-45e1-b49a-193c180696e4: Simple # Simple
    69664e00-8076-4c4d-84b6-47a79c6c4b4b: 'Text simple' # Text simple
    8576967a-62f7-4292-be16-7feac208effb: 'Entry > Capítol' # Entry > Capítol
    39561329-9989-45fe-b242-218cbe6b3e40: 'En present' # En present
    c6bc2c8d-cdc6-477a-9261-a424e03645a9: 'Entry > Llibre' # Entry > Llibre
    d779f0dc-9989-4bfc-a650-2dbbaf83669e: 'Text ric' # Text ric
    d2399b89-87b2-4f3a-9eb7-e311a405ef62: Persones # Persones
    eb6ec4e7-328d-48ed-902e-9bad2fb003e3: 'Entry > Persona' # Entry > Persona
    ee778f01-15ae-43a3-b335-e37f288be176: 'En present [ES]' # En present [ES]
    fe2f4045-02f4-41ad-a175-eb69191a1a05: Capítols # Capítols
    ff486d12-d94d-4a7f-b506-57c5a3c2e2e0: 'En present [CA]' # En present [CA]
plugins:
  author-toolbar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: ITHZDLWPGR4F99FG11MNVC7C
    schemaVersion: 3.0.13
system:
  edition: solo
  live: true
  name: 'En present'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
