defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2c316bdb-68c4-4420-97b1-e85e1c5d681e # Entry > Capítol
handle: entryCapitol
maxAuthors: 1
name: 'Entry > Capítol'
previewTargets:
  -
    label: 'Página de entrada principal'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ee778f01-15ae-43a3-b335-e37f288be176: # En present [ES]
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  ff486d12-d94d-4a7f-b506-57c5a3c2e2e0: # En present [CA]
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 6d10e833-a3a6-46e7-b342-2d974ec5f58b
type: structure
