defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6ad2c898-0cf3-4058-aa22-7c1986e5b049 # Entry > Persona
handle: entryPersona
maxAuthors: 1
name: 'Entry > Persona'
previewTargets:
  -
    label: 'Página de entrada principal'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  033dacc8-df7a-4550-a5fc-ebae2179714e: # Privada [CA]
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  ee778f01-15ae-43a3-b335-e37f288be176: # Pública [ES]
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  f55d6348-8ad5-414d-88c7-a50044a897c1: # Privada [ES]
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  ff486d12-d94d-4a7f-b506-57c5a3c2e2e0: # Pública [CA]
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
