defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b0f3ccf5-cdc5-47e5-bb3e-e83014e862a3 # Entry > Recurs > Resum
  -
    uid: 7e586577-127c-46df-b92d-db3f6f2b3d6f # Entry > Recurs > Pregunta
  -
    uid: b0588da5-48d5-4745-abed-464ae1811973 # Entry > Recurs > Enllaç
handle: entryRecurs
maxAuthors: 1
name: 'Entry > Recurs'
previewTargets:
  -
    label: 'Página de entrada principal'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  033dacc8-df7a-4550-a5fc-ebae2179714e: # Privada [CA]
    enabledByDefault: true
    hasUrls: true
    template: entry-recurs/_entry.twig
    uriFormat: 'entry-recurs/{slug}'
  ee778f01-15ae-43a3-b335-e37f288be176: # Pública [ES]
    enabledByDefault: true
    hasUrls: true
    template: entry-recurs/_entry.twig
    uriFormat: 'entry-recurs/{slug}'
  f55d6348-8ad5-414d-88c7-a50044a897c1: # Privada [ES]
    enabledByDefault: true
    hasUrls: true
    template: entry-recurs/_entry.twig
    uriFormat: 'entry-recurs/{slug}'
  ff486d12-d94d-4a7f-b506-57c5a3c2e2e0: # Pública [CA]
    enabledByDefault: true
    hasUrls: true
    template: entry-recurs/_entry.twig
    uriFormat: 'entry-recurs/{slug}'
type: channel
