defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: cb37151f-e76e-41e9-a558-2a2217f85e26 # Page > Home
handle: pageHome
maxAuthors: 1
name: 'Page > Home'
previewTargets:
  -
    label: 'Página de entrada principal'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ee778f01-15ae-43a3-b335-e37f288be176: # Pública [ES]
    enabledByDefault: true
    hasUrls: true
    template: publica/pages/home-page.twig
    uriFormat: __home__
  ff486d12-d94d-4a7f-b506-57c5a3c2e2e0: # Pública [CA]
    enabledByDefault: true
    hasUrls: true
    template: publica/pages/home-page.twig
    uriFormat: __home__
type: single
